export default {
	language_code: "ko",
	general: {
		add: "추가",
		alarm: "알림",
		all: "전체",
		apply: "적용하다",
		audios: "오디오",
		back: "뒤로 가기",
		check: "확인하다",
		cancel_popup: "확인",
		cancel: "취소",
		close: "닫기",
		confirm_delete: "구술녹음 삭제",
		confirm: "확인",
		create: "생성",
		createv2: "만들기",
		day: "일",
		delete_all_forever: "삭제",
		delete_all_trash: "휴지통 비우기",
		delete_all: "휴지통 비우기",
		delete: "삭제",
		disable_2: "사용 안 함",
		disable: "비활성화",
		done: "끝난",
		download: "다운로드",
		edit: "수정",
		empty_items: "데이터 없음",
		enable_2: "사용",
		enable: "활성화",
		expand: "확장하다",
		from: "부터",
		go: "가다",
		high: "고화질(원본)",
		images: "이미지",
		load_theme: "테마로드 중 ...",
		loaded: "박은",
		loading: "로딩",
		low: "저화질",
		modify: "수정",
		month_1: "일월",
		month_10: "십월",
		month_11: "십일월",
		month_12: "십이 월",
		month_2: "이월",
		month_3: "삼월",
		month_4: "사월",
		month_5: "오월",
		month_6: "유월",
		month_7: "칠월",
		month_8: "팔월",
		month_9: "구월",
		month: "월",
		move: "이동",
		no_data: "데이터 없음",
		no_name: "이름 없음",
		no: "취소",
		none: "없음",
		notice: "알림",
		notification: "알림",
		ok: "확인",
		pause: "중지",
		photos: "이미지",
		refresh: "초기화",
		registration: "등록",
		reset_all: "모두 초기화",
		reset: "초기화",
		restore_all_trash: "모두 복원",
		restore_all: "복원",
		save: "저장",
		search_placeholder: "이미지나 비디오를 검색하세요",
		search: "검색",
		select_opt: "옵션 선택 ...",
		select: "선택",
		selected_2: "개 선택",
		selected: "개 선택",
		share: "공유",
		standard: "일반화질",
		text_delete: "삭제 하시겠습니까",
		text_time_out: "끝났어.",
		timeout: "시간 초과",
		to: "까지",
		videos: "비디오",
		viewmore: "더보기",
		year: "년",
		yes_popup: "확인",
		yes: "이동",
		id_duplicate: "ID 중복 확인",
		email_duplicate: "이메일 중복 확인",
	},
	alert: {
		error: "오류",
		warning: "경고",
		notice: "알림",
		success: "성공",
		confirm: "확인",
		alert: "알림",
		appInfo:
			"앱 이름을 가져올 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		login_non_exist_email: "등록되지 않은 계정입니다.",
		login_wrong_password: "입력하신 계정 정보가 일치하지 않습니다.",
		unactivated_user:
			"관리자 승인이 진행 중입니다.\n승인이 완료될 때까지 기다려주십시오.",
		loginFailTimeHandle: (time) =>
			`입력하신 계정정보가 일치하지 않습니다. (<span style="color:#009BDB">${time}</span>/5회)\n5회 연속 오류 시 로그인 할 수 없습니다.`,
		login_1: "계정이 없습니다!",
		login_2: "문제가 발생했습니다. 나중에 다시 시도하세요!",
		login_3: "일치하는 계정 정보를 찾을 수 없습니다.",
		login_4: "성공적으로 등록했습니다. 이메일을 확인하여 계정을 확인하십시오!",
		login_5: "비밀번호 수정을 위한 메일을 보냈습니다.\n 메일함을 확인해주세요.",
		login_6: "비밀번호가 틀렸습니다.",
		login_7:
			"사용자 인증이 필요한 이메일입니다.\n 이메일 인증 후 로그인해주세요.",
		login_8: "인증되지 않은 이메일입니다. \n 메일함을 확인해 인증해주세요.",
		register_1: "이미 등록된 이메일입니다.",
		register_exists: "이메일이 이미 존재합니다",
		register_2: "이 로그인 이름은 이미 등록되어 있습니다",
		register_3: "이 전화는 이미 등록되었습니다",
		register_4: "이메일 재전송 성공!\n 이메일을 다시 확인해 주세요.",
		id_exists: "이미 등록된 아이디입니다.",
		storage_1:
			"저장 용량 할당을받을 수 없습니다. 페이지를 새로 고침하거나 나중에 다시 시도하세요!",
		storage_2:
			"스토리지 할당을 생성 할 수 없습니다. 페이지를 새로 고침하거나 나중에 다시 시도하세요!",
		ingest_1:
			"수집 구성을 가져올 수 없습니다. 페이지를 새로 고침하거나 나중에 다시 시도하세요!",
		ingest_2:
			"수집 구성을 만들 수 없습니다. 페이지를 새로 고침하거나 나중에 다시 시도하세요!",
		outgest_1:
			"아웃 제스트 구성을 가져올 수 없습니다. 페이지를 새로 고침하거나 나중에 다시 시도하세요!",
		outgest_2:
			"아웃 제스트 구성을 만들 수 없습니다. 페이지를 새로 고침하거나 나중에 다시 시도하세요!",
		task_1:
			"서비스를 받을 수 없습니다. 백 페이지를 다운로드하거나 나중에 다시 시도하십시오.",
		task_2:
			"서비스를 생성할 수 없습니다. 백 페이지를 다운로드하거나 이후에 다시 시도하십시오.",
		audioassets_1:
			"자산의 오디오를 가져올 수 없습니다. 페이지를 새로 고침하거나 나중에 다시 시도하세요!",
		audioassets_2:
			"자산의 오디오를 생성 할 수 없습니다. 페이지를 새로 고침하거나 나중에 다시 시도하세요!",
		cat_1:
			"폴더 정보를 가져올 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		cat_2:
			"폴더를 만들 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		cat_3:
			"카테고리 폴더의 이름을 바꿀 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		cat_4:
			"카테고리 폴더를 삭제할 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		cat_5:
			"카테고리의 폴더를 이동할 수 없습니다. 페이지를 새로고침하거나 나중에 다시 시도하세요!",
		com_accept:
			"이 커뮤니티를 수락할 수 없습니다. 페이지를 새로고침하거나 나중에 다시 시도하세요!",
		com_create_1:
			"커뮤니티를 만들 수 없습니다. 페이지를 새로고침하거나 나중에 다시 시도하세요!",
		com_edit_1:
			"커뮤니티를 수정할 수 없습니다. 페이지를 새로고침하거나 나중에 다시 시도하세요!",
		com_invite_1:
			"사용자를 커뮤니티에 초대할 수 없습니다. 페이지를 새로고침하거나 나중에 다시 시도하십시오!",
		com_invite_url_exp:
			"링크가 만료되어 커뮤니티에 가입할 수 없습니다. 새 링크로 다시 시도하세요!",
		com_invite_url_invalid:
			"링크가 잘못되었습니다. 커뮤니티에 가입할 수 없습니다. 새 링크로 다시 시도하십시오!",
		com_invite_already_a_member: "이미 가입했습니다.",
		com_invite_url_unknown:
			"알 수 없는 링크입니다. 커뮤니티에 가입할 수 없습니다. 새 링크로 다시 시도하세요!",
		com_invite_2: "이미 초대된 회원입니다.",
		tag_1:
			"태그 색상과 이름을 가져올 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		tag_2:
			"새 태그를 추가 할 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		tag_3:
			"태그를 수정할 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		tag_4:
			"태그를 삭제할 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		sto_1:
			"저장 용량을 사용할 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		img_1:
			"목록 이미지를 가져올 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		img_2:
			"지금이 이미지에 태그를 추가 할 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		img_3:
			"지금이 이미지에 대한 태그를 제거 할 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		img_4:
			"지금은이 작업을 수행 할 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		time_1:
			"타임 라인을 가져올 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		pro_1:
			"프로필 정보를 가져올 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		pro_2: "비밀번호를 변경할 수 없습니다.\n입력한 정보를 확인해주세요.",
		pro_3:
			"서버에 요청을 보낼 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		up_1: "업로드 실패 – 지원하지 않는 포맷 ",
		up_2: "파일이 너무 큽니다! 500MB 이하의 파일만 업로드할 수 있습니다.",
		up_3: "파일이 복제되었으며 건너 뛰었습니다!",
		up_4: "이 이미지 URL은 서버 자체에 의해 차단되었습니다. 다른 URL로 시도하십시오!",
		up_5: "파일 업로드 파일",
		up_6: "이미지 크기 가져오기 실패",
		up_video:
			"파일이 너무 큽니다! 4GB 이하의 동영상 파일만 업로드할 수 있습니다.",
		up_audio:
			"파일이 너무 큽니다! 4GB 이하의 오디오 파일만 업로드할 수 있습니다.",
		up_image:
			"파일이 너무 큽니다! 200MB 이하의 이미지 파일만 업로드할 수 있습니다.",
		up_document:
			"파일이 너무 큽니다! 500MB 미만의 문서 파일만 업로드할 수 있습니다.",
		up_model:
			"파일이 너무 큽니다! 500MB 미만의 모델 파일만 업로드할 수 있습니다.",
		up_other: "파일이 너무 큽니다! 500MB 미만의 파일만 업로드할 수 있습니다.",
		up_size_0: "파일 크기가 0이거나 파일이 손상되었습니다.",
		face_1:
			"얼굴 목록을 가져올 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		face_2:
			"지금이 얼굴을 삭제할 수 없습니다. 페이지를 새로고침(F5)하거나 나중에 다시 시도하세요!",
		face_3: "이 이미지에서 서버로 얼굴을 업로드 할 수 없습니다!",
		download_failed: "오류로 인해 이미지를 다운로드할 수 없습니다",
		major_face: "이 얼굴은 이 사람의 주요 얼굴이므로 삭제할 수 없습니다.",
		upload_progress_exist:
			"업로드가 진행 중입니다. \n계속하려면 이전 업로드를 완료하세요.",
		delete_narration_title: "나레이션 삭제",
		delete_narration_text:
			"'{value}'을 삭제하시겠습니까?\n삭제한 나레이션은 복원할 수 없습니다.",
		delete_narration_text2:
			"선택한 나레이션을 삭제하시겠습니까?\n삭제한 나레이션은 복원할 수 없습니다.",
		success_count: "성공 {value}",
		failure_count: "실패 {value}",
		permission_microphone:
			"나레이션 녹음을 위해 \n마이크 권한을 허용해 주세요.",
		empty_search_value: "검색어를 입력해주세요.",
		login_fail_alert:
			"입력하신 계정정보가 일치하지 않습니다.\n5회 연속 오류 시 로그인이 제한됩니다.",
		login_restriction: `<span style="color:#F03529">5회 연속 계정정보  입력 오류</span>로 \n로그인이 제한되었습니다.\n비밀번호 재설정 후 로그인해주세요.`,
		login_reset_password: "비밀번호 재설정",
		times: "회",
		login_error: "로그인 오류",
		community_pause:
			"관리자가 커뮤니티를 일시정지하여 \n커뮤니티에 접속할 수 없습니다",
		change_password_content_1: "정보를 업데이트 했습니다.",
		change_password_content_2:
			"비밀번호를 변경할 수 없습니다.\n입력한 정보를 확인해주세요.",
		update_category_order: "카테고리 순서가 변경되었습니다.",
	},
	topmenu: {
		config: "설정",
		profile: "개인 정보",
		logout: "로그아웃",
		admin_dashboard: "설정",
		upload: "업로드",
		theme: "테마",
		language: "언어",
		listFace: "얼굴 목록",
		faceSearch: "얼굴",
		noFaceFound: "얼굴을 찾을 수 없습니다!",
		location: "장소",
		pickLocation: "장소 선택...",
		searchLocation: "장소 검색",
		noResultFound: "검색된 결과가 없습니다",
		noPermission: "장소 액세스 권한이 없습니다.",
		profile_setting: "개인정보",
		language_setting: "언어설정",
		dark_mode: "다크모드",
		light_mode: "라이트모드",
		search_for_place: "장소를 검색하세요",
		setting: "사용자설정",
	},
	categories: {
		my_drive: "나의 아카이브",
		public: "내가 공유한 이미지",
		community: "커뮤니티",
		trash: "휴지통",
		filter: "필터",
		category: "폴더",
		image_format: "파일 형식",
		size: "파일 크기",
		share: "공유",
		upload_date: "촬영일자",
		tag_color: "태그",
		storage: "스토리지 정보",
		remove_tag_filter: "태그 리셋",
		large: "대용량 (>10MB)",
		large_2: "대용량",
		medium: "중간 (1~10MB)",
		medium_2: "중간",
		small: "작음 (<1MB)",
		small_2: "작음",
		custom_size: "직접 입력",
		ratio: "비율",
		quality: "화질",
		tall: "세로",
		wide: "가로",
		square: "정사각형",
		quality_high: "고화질",
		quality_high_tooltip: "- 길이 또는 높이가 1920px보다 큼",
		quality_medium: "보통",
		quality_medium_tooltip: "- 길이 또는 높이가 512~1920px 사이",
		quality_low: "저화질",
		quality_low_tooltip: "- 길이 또는 높이가 512 픽셀 이하",
		today: "오늘",
		last_week: "지난 일주일",
		last_month: "지난 한 달",
		direct_input: "직접 입력",
		apply: "적용하다",
		file_format: "파일 형식",
		period: "촬영일자",
	},
	tag: {
		empty_tag: "아직 태그가 없습니다!",
		contain_all: "모든 태그가 포함되어 더이상 추가할 수 없습니다!",
		remove_tag: "태그 제거",
		add_tag: "태그 추가",
		index: "번호",
		name: "태그 이름",
		color: "컬러",
		title_custom: "커스텀 태그",
		title_edit: "태그 편집",
		title_add: "태그 추가",
		tag_name: "태그 이름",
		tag_color: "태그 컬러",
		title_error: "제목은 1자에서 64자 이내여야 합니다!",
	},
	preview: {
		guide_text:
			"미리보기를 보려면 이미지를 선택하세요. <kbd>Ctrl</kbd> 키 또는 <kbd>Shift</kbd> 키를 누른 상태에서 클릭하면 여러 항목을 선택할 수 있습니다.",
		more_detail: "세부정보 더보기",
	},
	metadata: {
		meta_title: "메타데이터",
		file_meta_title: "파일 메타데이터",
		files: "파일",
		file_extension: "파일 확장자",
		size: "용량",
		mime_type: "MIME 유형",
		resolution: "해상도",
		audio_bitrate: "오디오 비트레이트",
		audio_channel: "오디오 채널",
		audio_codec: "오디오 코덱",
		video_bitrate: "비디오 비트레이트",
		video_codec: "비디오 코덱",
		video_frameRate: "비디오 프레임 속도",
		video_resolution: "동영상 해상도",
		created_date: "만든 날짜",
		last_modified: "마지막 수정 날짜",
		duration: "길이",
		metadata: "메타데이터",
		custom_metadata: "커스텀 메타데이터",
		software: "소프트웨어",
		number: "번호",
		iso: "ISO 등급",
		title: "제목",
		desc: "설명",
		position: "위치",
		location: "위치",
		narrations: "나레이션",
		upload_date: "등록일",
		creation_date: "등록 일시",
		last_modified_date: "수정일",
		creator: "등록자",
		exif: {
			exifDateTimeOriginal: "촬영일자",
			exifMake: "카메라 제조사",
			exifModel: "카메라 모델명",
			exifFocalLength: "초점 거리",
			exifFNumber: "F-스톱",
			exifISO: "ISO 감도",
			exifExposureTime: "노출 시간",
			exifExposureProgram: "노출 프로그램",
			exifFlash: "플래시",
			exifGPSLatitude: "GPS 위도",
			exifGPSLongitude: "GPS 경도",
			exifOrientation: "방향",
			exifModifyDate: "수정일자",
			exifDataTimeDigitized: "디지털화 데이터 시간",
			exifColorSpace: "색 공간",
			exifMeteringMode: "측광 모드",
			exifPixelXDimension: "픽셀 X 차원",
			exifPixelYDimension: "픽셀 Y 차원",
			exifExposureBiasValue: "노출 바이어스",
			exifMaxApertureValue: "조리개 최대 개방",
			exifSoftware: "소프트웨어",
			exifLightSource: "광원",
			exifImageDescription: "이미지 설명",
			exifExifVersion: "Exif 버전",
			exifUserComment: "사용자 설명",
			exifComponentsConfiguration: "구성 요소 구성",
			exifCompressedBitsPerPixel: "픽셀 당 압축 비트",
		},
		string: "텍스트",
		text: "텍스트",
		string_options: "목록",
		list: "목록",
		date: "날짜",
		option: "옵션",
	},
	status: {
		all: "전체",
		completed: "성공",
		failed: "실패",
	},
	filter_tool: {
		period: "기간",
		status: "상태",
		mediaType: "미디어 타입",
		category: "카테고리",
		search: "검색",
		archive: "나의 아카이브",
		selectF: "나의 아카이브",
		title: "제목",
		fileName: "제목",
	},
	folder: {
		create_folder: "새 카테고리",
		create_folder_community: "커뮤니티 카테고리 만들기",
		create_inside: "새 폴더 생성",
		root_folder: "최상위 폴더",
		enter_name: "카테고리 이름을 입력해주세요",
		name_error: "폴더 이름은 1자에서 128자 이내여야 합니다!",
		name_Category_error: "카테고리 이름은 1-128자 이내여야 합니다.",
		name_community_error: "커뮤니티 이름은 1-128자 이내여야 합니다.",
		move_folder: "카테고리 이동",
		current_folder: "현재 폴더",
		move_to: "카테고리 이동",
		share_to: "공유",
		choose_folder: "이동할 새 폴더 선택",
		rename_title: "카테고리 이름 변경",
		delete_folder: "폴더 삭제",
		restore_folder: "폴더 복원",
		delete_text_1:
			"먼저 모든 하위 폴더와 이미지가이 폴더에 포함 된 것을 삭제해야합니다!",
		delete_text_2: "{value}을(를) 삭제하시겠습니까?",
		delete_text_3:
			"{value} 및 내부의 모든 항목을 삭제하시겠습니까? 영구적으로 삭제되며 실행 취소할 수 없습니다.",
		add_new_folder: "새 카테고리",
		same_id_err:
			"현재 폴더는 대상 폴더와 동일합니다. 다른 폴더를 선택하십시오!",
		restore_text_1: "{value} 및 내부의 모든 자산을 복원하시겠습니까?",
		category: "카테고리",
		location: "카테고리",
		creating_folders: "카테고리를 만드는 중입니다. 잠시만 기다려 주십시오...",
		move_to_trash_title: "휴지통으로 이동",
		move_to_trash_text:
			"선택한 항목을 휴지통으로 이동 하시겠습니까? 이동한 항목은 휴지통에서 복원할 수 있습니다.",
	},
	imageLayout: {
		subfolder: "하위 폴더",
		choose_items: "카테고리 선택",
		empty: "빈",
		restore: "복원",
		text_restore: "선택한 항목을 복원하시겠습니까?",
		restore_selected_item: "선택한 항목을 복원하시겠습니까?",
		text_restore_2: "선택한 항목을 복원하시겠습니까?",
		delete: "영구 삭제",
		text_delete_1:
			"선택한 항목을 영구적으로 삭제하시겠습니까? \n 삭제한 후에는 복원할 수 없습니다.",
		text_delete_3:
			"선택한 항목을 휴지통으로 이동 하시겠습니까?\n 이동한 항목은 휴지통에서 복원할 수 있습니다.",
		text_delete_4:
			"선택한 항목을 영구적으로 삭제하시겠습니까?\n 삭제한 후에는 복원할 수 없습니다.",
		trash: "영구 삭제",
		text_trash_1:
			"선택한 항목을 휴지통으로 이동 하시겠습니까?\n이동한 항목은 휴지통에서 복원할 수 있습니다.",
		move_to_trash: "이동",
		move_to_trash_title: "휴지통으로 이동",
		move_to_trash_text:
			"선택한 항목을 휴지통으로 이동 하시겠습니까?\n이동한 항목은 휴지통에서 복원할 수 있습니다.",
		thumbnail: "썸네일",
		name: "이름",
		tag: "태그",
		resolution: "해상도",
		created_day: "생성일",
		size: "크기",
		updated_day: "마지막 업데이트",
		no_img: "표시할 이미지가 없습니다!",
		latest: "최신순",
		earliest: "등록일순",
		a_z: "제목",
		z_a: "제목",
		shooting_date: "촬영일",
		last_most_day: "수정일",
		reg_date: "등록일",
		title: "제목",
		selected_items: "유산",
		selected_folders: "폴더",
		drop_img: "현재 폴더에 업로드하려면 여기에 이미지를 드롭하세요.",
		drop_img1:
			"파일이나 폴더를 이곳에 끌어다 놓거나 파일 업로드 버튼을 클릭하세요.",
		drop_img2: [
			"Image (png, jpeg, gif, webp, svg, bmp, avif, tiff, ...)",
			"Audio (mpeg, wave, wav, mp3, ...)",
			"Video (mp4, mjpeg, mov, web, avi, ...)",
			"Document (pdf, docx, ppt, text, html, ...)",
		],
		upload_title: "파일 업로드",
		uploading: "파일 업로드 중",
		upload_complete: "파일 업로드 완료",
		upload_failed: "파일 업로드 중지",
		uploaded: "업로드 완료",
		failed: "업로드 실패",
		failed_canceled: "업로드 실패 – 취소",
		canceled: "업로드 실패",
		goto_upload_location: "업로드 위치로 이동하기",
		cancel_upload: "업로드 취소",
		continue_upload: "업로드 계속",
		stay: "머무르기",
		leave: "이동하기",
		retry_upload: "재시도",
		stop_upload: "중지",
		resume_upload: "다시 시작",
		enterUrl: "URL 업로드",
		enterUrlImg: "이미지의 URL을 입력하세요",
		upload: "업로드",
		timeline: "타임 라인",
		alphabet: "알파벳",
		most_similar: "가장 유사한",
		toggle_timeline: "타임 라인 모드 전환",
		warning: "경고",
		text_warning_max: "오디오 수가 3 개 한도에 도달했습니다.",
		add_a_title: "제목 추가",
		add_a_desc: "설명 추가",
		add_a_value: "사용자 메타데이터 입력",
		faces: "얼굴",
		audio_desc: "나레이션 설명 보기",
		origin_name: "원래 이름",
		showSubFile: "하위파일 모두보기",
		move_items: "카테고리 이동",
		share_items: "공유",
		select_items: "폴더 선택",
		location: "위치",
		current_location: "현재 위치",
		move_location: "이동 위치",
		multi_location: "다중 위치",
		move_folder_guide: "이동할 카테고리를 선택하세요.",
		move_folder_guide_2: "조회할 카테고리를 선택하세요.",
		move_folder_guide_3: "공유할 커뮤니티를 선택하세요.",
		no_folder_1: "이동할 수 있는 폴더가 없습니다.",
		no_folder_2: "새 폴더 추가 버튼을 통해 이동할 폴더를 만들어주세요.",
		compress_file: "압축 파일로 받기",
		separate_file: "개별 파일로 받기",
		download_alert:
			"{value} 개의 이미지를 선택하셨습니다.\n 다운로드 하시겠습니까?",
		download_limit_title: "알림",
		download_limit: "최대 300개까지 파일을 다운로드 할 수 있습니다.",
		download_limit_confirm: "확인",
		upload_file_invalid:
			"파일이 잘못되었거나 비어 있습니다! 이미지, 비디오 또는 오디오 파일 형식만 선택할 수 있습니다.",
		prepare_upload: "업로드를 준비 중입니다. 잠시만 기다려 주십시오...",
		subcategory: "하위 카테고리",
		empty_asset: "카테고리가 비어있습니다. \n+를 눌러 파일을 추가하세요.",
		empty_trash: "휴지통이 비어 있습니다.",
		empty_search: "검색 결과가 없습니다.",
		selected_items_mobile: "개 선택됨",
		empty_asset_desktop_1: "mymy 아카이브가 비어 있습니다.",
		empty_asset_desktop_2:
			"파일이나 폴더를 여기 끌어다 놓거나 업로드 버튼을 클릭하세요.",
		empty_community_desktop_1:
			"MYMY Archive에 보관 중인 사진을 함께 볼 수 있어요. \n 커뮤니티에 함께 볼 미디어를 업로드해보세요.",
		empty_community_desktop_2: "커뮤니티 회원은 100명까지 초대할 수 있습니다.",
		waiting_community_desktop_1:
			"MYMY Archive에 보관 중인 사진을 함께 볼 수 있어요.",
		waiting_community_desktop_2: "커뮤니티에 함께 볼 미디어를 업로드해보세요.",
		file_upload: "파일 선택",
		file_upload_2: "파일 업로드",
		url_upload_guide:
			"이미지의 {value}을 복사해 이미지를 업로드 할 수 있습니다.",
		url_upload_guide_2:
			"파일이나 폴더를 이곳에 끌어다 놓거나 파일 업로드 버튼을 클릭하세요",
		title_notice: "알림",
		title_alert: "알림",
		content_notice: "업로드 창을 닫으면 업로드가 취소됩니다. 취소하시겠습니까?",
		content_notice2:
			"페이지를 벗어나시겠습니까?\n진행중인 업로드가 취소될 수 있습니다.",
		trash_info: "휴지통에 있는 항목은 90일 후에 완전히 삭제됩니다.",
		trash_info2: "휴지통에 있는 항목은 관리자의 승인 후에 완전히 삭제됩니다.",
		fail_image_content_1: "이미지를 로드할 수 없습니다.",
		fail_image_content_2: "이미지를 로드하는 도중 오류가 발생했습니다.",
		fail_audio_content_1: "오디오 이미지를 로드할 수 없습니다.",
		fail_audio_content_2: "이미지를 로드하는 도중 오류가 발생했습니다.",
		fail_video_content_1: "비디오를 로드할 수 없습니다.",
		fail_video_content_2: "비디오를 로드하는 도중 오류가 발생했습니다.",
		fail_document_content_1: "문서를 불러올 수 없습니다.",
		fail_document_content_2: "문서 불러오기 오류.",
		audio_image_edit: "오디오 이미지 등록",
	},
	contextMenu: {
		view: "이미지 보기",
		restore_title: "복원",
		restore_text: "선택한 항목을 복원하시겠습니까?",
		edit: "메타데이터 편집",
		move: "이동",
		delete: "삭제",
		delete_forever_title: "영구 삭제",
		delete_forever_text:
			"선택한 항목을 영구적으로 삭제하시겠습니까?\n 삭제한 후에는 복원할 수 없습니다",
		delete_forever_text2: "선택한 항목을을 삭제 하시겠습니까?",
		restore_all_title: "모두 복원",
		restore_all_text: "모든 항목을 복원하시겠습니까?",
		delete_all_title: "휴지통 비우기",
		delete_all_text:
			"모든 항목을 영구적으로 삭제하시겠습니까?\n 삭제한 후에는 복원할 수 없습니다",
		delete_category_title: "카테고리 삭제",
		delete_category_text:
			"이 카테고리를 삭제하시겠습니까?\n 삭제된 항목은 복구할 수 없습니다",
		request_delete_category_title: "관리자에게 카테고리 삭제 요청",
		request_delete_category_text:
			"이 카테고리 삭제 요청을 제출하시겠습니까?\n 귀하의 요청은 관리자에게 전송됩니다",
		request_delete_assets_title: "관리자에게 삭제 요청",
		request_delete_assets_text:
			"이 자산 삭제 요청을 제출하시겠습니까?\n 귀하의 요청은 관리자에게 전송됩니다",
		request_delete_assets_text2: "선택한 항목을을 삭제 하시겠습니까?",
		request_delete_list_file_title: "관리자에게 삭제 요청",
		request_delete_list_file_text:
			"이 목록 파일 삭제 요청을 제출하시겠습니까?\n 귀하의 요청은 관리자에게 전송됩니다",
		warning_permission: "권한 경고",
		warning_permission_text:
			"카테고리를 삭제하거나 자산을 삭제할 수 있는 권한이 없습니다. 항목을 다시 선택하십시오.",
		reselect: "재선택",
		send_request: "요청 보내기",
		download_thumb: "썸네일 다운로드",
		download_full: "원본 다운로드",
		new_folder: "새 카테고리",
		rename: "이름 변경",
		move_folder: "이동",
	},
	detailAsset: {
		desc_error: "내용은 300자 미만이어야합니다.",
		title_error: "제목의 길이는 1자 이상, 256자 미만이어야합니다.",
		share: "공유",
		hide_info: "메타데이터 숨기기",
		copied: "복사 됨!",
		find_in_mymy: "오디오 이미지 업로드",
		find_on_my_device: "내 기기에서 찾기",
		upload_cover_btn: "업로드",
	},
	profile: {
		cancel_description: "가입 해지",
		change_email: "이메일 변경",
		change_info: "개인정보 변경",
		change_password: "비밀번호 변경",
		col_custom: "열 목록",
		daily_traffic: "일간 트래픽",
		day_exp1: "DD (예: 01)",
		day_exp2: "DD 일 (예: 01 일)",
		day_exp3: "일 DD (예: 일 01)",
		day_format: "일 형식",
		delete_info: "계정 삭제", //
		department_placeholder: "부서명을 입력하세요.",
		displayName: "이름",
		download: "다운로드",
		email_verify_1: "이메일이 확인되지 않았습니다!",
		email_verify_2: "확인하려면 이메일을 확인하십시오!",
		email_verify_3: "지금 인증하십시오.",
		email: "이메일",
		enter_new_password: "새 비밀번호를 입력하세요",
		enter_old_password: "현재 비밀번호를 입력하세요",
		firstName: "이름",
		folder: "폴더",
		forgot: "비밀번호를 잊으셨나요?",
		get_password: "새 비밀번호 받기",
		goto_change_password: "비밀번호 변경하러 가기",
		help: "도움말",
		image: "이미지",
		in_use: "사용중",
		join_in: "회원가입",
		lastName: "성",
		login_page: "로그인 페이지",
		login: "로그인",
		loginName: "로그인 아이디",
		mess_error_email: "잘못된 이메일 주소입니다!",
		mess_error_firstName: "이름은 4자에서 64자 이내여야 합니다.",
		mess_error_lastName: "성은 4자에서 64자 이내여야 합니다.",
		mess_error_loginName:
			"로그인 아이디은 공백이나 특수 문자를 포함하지 않으며 4자에서 18자 이내여야 합니다.",
		mess_error_password:
			"비밀번호는 공백을 포함하지 않으며  4자에서 64자 이내여야합니다.",
		mess_error_phone: "전화번호는 문자를 포함할 수 없습니다.",
		mess_error_rePassword: "암호가 동일하지 않습니다!",
		mobilePhone: "전화 번호",
		month_exp1: "MM (예: 01)",
		month_exp2: "mmm (예: Jan)",
		month_exp3: "MMM (예: JAN)",
		month_exp4: "mmmm (예: January)",
		month_exp5: "달 MM (예: 달 01)",
		month_exp6: "MM 달 (예: 01 달)",
		month_format: "월 형식",
		my_gallery: "내 갤러리",
		newPassword: "새 비밀번호",
		next: "다음 단계",
		notice_1: "가입 해지가 완료되었습니다.",
		notice_2: "비밀번호를 확인해주세요.",
		notice_success_changepass: "비밀번호를 성공적으로 변경했습니다",
		oldPassword: "현재 비밀번호",
		or: "또는",
		password: "비밀번호",
		phone_number_placeholder: "전화번호를 입력하세요.",
		reason: "마이마이 가입을 해지하시려는 이유는 무엇인가요?",
		register: "회원가입",
		rePassword: "새 비밀번호 확인",
		reset_email_text:
			"등록된 이메일이 있습니다. \n등록된 이메일 정보를 초기화 하시겠습니까?",
		reset_email_title: "인증 메일 초기화",
		reset_email: "이메일 초기화",
		return_dashboard: "돌아가기",
		save_community_info: "커뮤니티 내 정보 변경",
		save_info: "정보 저장",
		tab_menu_0: "사용자 정보",
		tab_menu_1: "이메일",
		tab_menu_2: "비밀번호 변경",
		tab_menu_3: "통계",
		tab_menu_delete_Account: "가입 해지",
		tag: "태그",
		timeline_format: "타임 라인 형식",
		total: "전체 용량",
		update_success: "정보를 업데이트하였습니다.",
		update_success2: "저장되었습니다.",
		usage_storage: "스토리지 사용량",
		used: "사용량",
		user_statistic: "사용자 통계",
		wrong_password: "비밀번호가 틀렸습니다",
		year_exp1: "YYYY (예: 2021)",
		year_exp2: "년 YYYY (예: 년 2021)",
		year_exp3: "YYYY 년 (예: 2021 년)",
		year_format: "연도 형식",
	},
	landing: {
		banner_title: "여러분의 중요한 사진을 안전하게 보관하세요.",
		banner_subtitle:
			"MYMY 아카이브는 이미지를 클라우드와 오프라인에 안전하게 \n보관하고 언제든지 빠르게 찾을 수 있게 도와줍니다.",
		banner_subtitle_mobile:
			"MYMY 아카이브는 이미지를 클라우드와 \n오프라인에 안전하게 보관하고 언제든지 \n빠르게 찾을 수 있게 도와줍니다.",
		join_in: "무료로 가입하기",
		already_a_member: "이미 계정이 있으신가요?",
		login: "로그인",
		box_1_title: "어디서나 안전하게",
		box_1_description: "사진을 PC, 스마트폰 어디서든 \n안전하게 저장하세요.",
		box_2_title: "중요한 설명을 다세요",
		box_2_description: "사진에 대한 설명을 말로, 텍스트로 \n손쉽게 달아두세요.",
		box_3_title: "빠르게 찾으세요",
		box_3_description: "포함된 얼굴,장소, 시간으로 \n사진을 손쉽게 찾으세요.",
		box_4_title: "손쉽게 공유해요",
		box_4_description:
			"저장된 사진을 친구에게, 가족에게 \n손쉽게 SNS로 공유하세요.",
		address: "(08380) 서울 구로구 디지털로 33길 11, 408",
		phone_1: "+82-2-857-1101",
		phone_2: "+82-2-2025-7444",
		res_title: "완전히 반응",
		res_text: "유연한 액세스를 위해 모든 장치로 확장",
		per_title: "뛰어난 성능",
		per_text: "Ariel MAM과 함께 수년간의 경험을 바탕으로 구축되었습니다.",
		awe_title: "멋진 사용자 경험",
		awe_text: "탐색하기 쉬운 최신 인터페이스",
		mobile_title: "SLEEK - EASY - MOBILE",
		mobile_text:
			"GIMA 대시 보드는 모든 필수 디지털 자산에 빠르게 액세스 할 수있는 원 스톱 상점입니다.",
		contact_title: "문의하기",
		contact_text:
			"우리는 모든 질문에 답하기 위해 여기에 있습니다! 언제든지 문의 해주세요.",
		id: "아이디",
		rmb_id: "아이디 저장",
		enter_id: "아이디를 입력하세요",
		find_by_id: "아이디로 찾기",
		empty_id: "아이디를 입력해주세요.",
		invalid_id: "잘못된 형태의 아이디 입니다.",
		short_id: "잘못된 ID는 4자 이상이어야 합니다.",
		long_id: "최대 128자까지 입력하세요.",
		id_error_text_length: "4자-20자 이내 입력.",
		id_error_text_english: "20자 이내 영문, 숫자만 사용 가능합니다.​​",
		registered_id: "이미 등록된 아이디입니다.",
		department: "부서명",
		enter_department: "부서명을 입력하세요",
		mobile_number: "휴대전화번호",
		enter_mobile_number: "휴대전화번호를 입력하세요",
		phone_number: "전화번호",
		enter_phone_number: "전화번호를 입력하세요",
		email: "이메일",
		password: "비밀번호",
		rmb_email: "이메일 저장",
		rmb_auth: "자동 로그인",
		forgot_password: "계정 정보를 잊으셨나요? {value}를 클릭하세요",
		click_here: "여기",
		name: "이름",
		rePassword: "비밀번호 확인",
		phone: "휴대폰 번호",
		verify_phone: "인증",
		enter_email: "이메일을 입력하세요",
		enter_name: "이름을 입력하세요",
		enter_password: "비밀번호를 입력하세요",
		enter_rePassword: "비밀번호를 확인하세요",
		enter_phone: "휴대폰 번호를 입력하세요",
		term_confirm: "이용 약관, 개인정보 수집 및 이용에 동의합니다",
		signup_complete: "가입 신청",
		find_account: "계정찾기",
		find_password: "이메일로 찾기",
		find_by_email: "이메일로 찾기",
		forgot_password_title: "비밀번호 찾기",
		request_by_admin: "관리자 초기화 요청하기",
		request_by_admin_title: "관리자 초기화 요청",
		request_to_admin: "관리자에게 요청 보내기",
		find_by_phone: "휴대폰 번호로 찾기",
		reset_via_email: "이메일을 통해 비밀번호를 재설정 할 수 있습니다.",
		receive_password: "비밀번호 수정 메일 받기",
		empty_email: "이메일을 입력해주세요.",
		empty_password: "비밀번호를 입력해주세요.",
		invalid_email: "잘못된 형태의 이메일 입니다.",
		invalid_password: "유효하지 않은 비밀번호",
		invalid_rePassword: "비밀번호가 일치하지 않습니다.",
		invalid_department: "128자 이내로 입력하세요.",
		invalid_name: "2-32자 이내로 입력하세요.",
		invalid_phone: "유효하지 않은 전화 번호",
		short_password: "비밀번호는 4자 이상이어야 합니다",
		invalid_notice: "인증메일이 발송되었습니다. \n 메일함을 확인해주세요.",
		resend_email: "인증메일 다시 받기",
		account_verify: "계정 인증",
		account_verify_text:
			"{value}로\n발송된 메일을 확인해주세요.\n이메일 인증 후 회원가입이 완료됩니다.",
		account_verify_text_2:
			"사용자 인증이 필요한 이메일입니다.\n이메일 인증 후 로그인해주세요.",
		notice: "알림",
		invalid_password_1: "8~64자 이내로 입력하세요.",
		invalid_password_2:
			"8~64자 이내, 영문 대소문자· 숫자 ·특수문자를 조합하여 입력하세요.",
		invalid_password_3: "영문 대소문자· 숫자 ·특수문자를 조합하여 입력하세요.",
		invalid_password_4: "비밀번호는 기존 비밀번호와 동일합니다.",
		policy_text: `이 사이트는 reCAPTCHA에 의해 보호되며 Google \n<a href="https://policies.google.com/privacy">개인정보 보호정책</a> 및 <a href="https://policies.google.com/terms">이용 약관</a>이 적용됩니다.`,
		invalid_mobile_phone: "20자 이내로 입력하세요.",
		admin_approval_alert: "관리자 승인 후 회원가입이 완료됩니다.",
		title_alert: "알림",
		id_can_use: "사용할 수 있는 ID 입니다.",
		id_cannot_use: "사용할 수 없는 ID 입니다.",
		email_can_use: "사용할 수 있는 이메일입니다.",
		email_cannot_use: " 사용할 수 없는 이메일입니다.",
		register: "가입 신청",
	},
	account: {
		tab_delete_1: {
			title: "해지하시기 전에 확인해주세요.",
			content_1:
				"• 해지하신 계정으로 다시 마이마이 서비스를 이용할 수 없습니다.",
			content_2:
				"• 보관 중인 계정 정보와 미디어 모두 영구 삭제되어 복구할 수 없습니다. 가입 해지 전에 미디어를 백업해주세요.",
			label: "마이마이 가입을 해지하시려는 이유는 무엇인가요?",
			reason_Content: " 해지 사유를 입력해주세요. (10자 이상)",
		},
		tab_delete_2: {
			title: "삭제하려는 계정을 확인하십시오",
			content_1: "- 삭제된 계정으로 'MYMY Archive' 서비스를 사용할 수 없습니다",
			content_2:
				"- 모든 계정 정보와 미디어가 영구적으로 삭제되어 복구할 수 없습니다. 계정을 삭제하기 전에 미디어를 백업하십시오.",
			confirm:
				"가입 해지 시 마이마이 아카이브 이용 내역과 보관된 미디어의 영구 삭제에.\n대한 내용을 확인하였으며, 가입 해지 절차에 동의합니다. ",
			delete_account: "가입 해지",
			enter_password: " 비밀번호를 입력해주세요",
		},
		reason_0: "유용하지 않습니다",
		reason_1: "MYMY와 유사한 다른 서비스를 사용 중입니다",
		reason_2: "계정이 해킹당했습니다",
		reason_3: "개인정보 및 데이터의 보안이 염려됩니다.",
		reason_4: "사용 방법을 모르겠습니다",
		reason_5: "두 번째 계정을 만들었습니다",
		reason_6: "기타",
	},
	email_confirm: {
		unvalidate_email: "사용할 수 없는 이메일입니다.",
		help_request: "이메일을 다시 확인하시거나 관리자에게 문의해주세요.",
		link_expire: "인증기간이 만료되었습니다.",
		resend_email: "인증 메일을 다시 보내시려면 아래 버튼을 클릭하세요.",
		resend_button: "인증 메일 다시 받기 ",
		contact_button: "관리자에게 문의하기",
		join_success: "가입이 완료되었습니다!",
		join_inform:
			"환영합니다! 이제 MYMY ARCHIVE의 서비스를 모두 이용할 수 있습니다.",
		sign_in_button: "로그인하러가기",
		registered_id: "가입 완료된 ID",
	},
	reset_password: {
		title_1: "비밀번호 변경",
		title_2: "새로운 비밀번호를 설정하세요",
		newPassword: "새 비밀번호",
		rePassword: "새 비밀번호 확인",
		placeholder_newPassword: "새 비밀번호를 입력하세요",
		placeholder_rePassword: "새 비밀번호를 확인하세요",
		reset_password: "변경",
		invalid_password: "유효하지 않은 비밀번호",
		invalid_rePassword: "비밀번호가 일치하지 않습니다",
	},
	change_password: {
		title_1: "비밀번호 변경 안내",
		title_2: `개인정보 보호와 안전한 아카이브 사용을 위해 <br /><span class="span">3개월마다</span> 비밀번호 변경하는 것을 권장하고 있습니다.<br />비밀번호는 주기적으로 변경해 사용하는 것이 안전합니다. `,
		oldPassword: "현재 비밀번호",
		newPassword: "새 비밀번호",
		rePassword: "새 비밀번호 확인",
		placeholder_oldPassword: "현재 비밀번호를 입력하세요",
		placeholder_newPassword: "새 비밀번호를 입력하세요",
		placeholder_rePassword: "새 비밀번호를 확인하세요",
		change_password: "비밀번호 변경",
		change_later: "나중에 변경하기",
		invalid_password: "유효하지 않은 비밀번호",
		invalid_rePassword: "비밀번호가 일치하지 않습니다",
	},
	setting: {
		failed_suport: "실패: 지원하지 않는 포맷 ",
		failed: "실패: 실패",
		success: "성공",
		data_usage: "사용량",
		total_usage: "전체 사용량", //이미지/비디오/오디오
		title_data_usage: "사용량",
		title_metadata: "메타데이터 관리",
		title_category: "카테고리 관리",
		images: "이미지",
		photo: "이미지",
		video: "비디오",
		audio: "오디오",
		metadata_title: "메타데이터 관리",
		upload_title: "업로드 관리",
		download_title: "다운로드 관리",
		category_title: "카테고리 관리",
		metadata_placeholder_opt: "하나 이상의 옵션을 입력해주세요",
		face_title: "얼굴 관리",
		add: "등록",
		search_placeholder: "검색어를 입력하세요",
		metadata_name: "메타데이터 이름",
		metadata_type: "형식",
		metadata_active: "사용 여부",
		create_cmeta_title: "사용자 메타데이터",
		activate: "활성화",
		metadata_format: "메타데이터 형식",
		memo: "메모",
		enter_memo_placeholder: "메모를 입력하세요.",
		incorrect_title: "제목에 1자 이상의 문자가 있어야 합니다.",
		incorrect_options: "빈 옵션",
		alert_delete_metadata_title: "사용자 메타데이터 삭제",
		alert_delete_metadata:
			"“{value}”를 삭제하시겠습니까? \n삭제한 메타데이터는 복구할 수 없습니다.",
		alert_delete_upload_title: "업로드 기록 삭제",
		alert_delete_upload:
			"이력을 삭제하시겠습니까?  \n 원본 파일은 삭제되지 않습니다.",
		alert_delete_download_title: "다운로드 기록 삭제",
		alert_delete_title: "이력 삭제",
		alert_delete_download:
			"이력을 삭제하시겠습니까?  \n  원본 파일은 삭제되지 않습니다.",
		category_name: "카테고리 이름",
		create_date: "생성일자",
		update_date: "업데이트 일자",
		thumbnail_face: "얼굴",
		face_name: "제목",
		find_same_person: "같은 인물 찾기",
		related_faces: "관련 인물 얼굴",
		alert_delete: "“{value}”를 삭제하시겠습니까?",
		major_face: "대표 얼굴",
		title: "제목",
		category: "카테고리",
		size: "용량",
		date_download: "다운로드 일시",
		date_upload: "업로드 일시",
		date: "일시",
		status: "상태",
		fileName: "제목",
		boolen_type: "부울",
		text_type: "텍스트",
		date_type: "날짜",
		list_type: "목록",
		int_type: "정수",
		decimal_type: "소수",
		int_options_type: "정수 옵션",
	},
	community: {
		accept: "시작하기",
		inviteMember: "커뮤니티 초대",
		icon: "커뮤니티 아이콘",
		create_community: "커뮤니티 등록",
		edit_community: "커뮤니티 수정",
		inviteByLink: "링크로 초대",
		inviteByAccount: "mymy 계정으로 초대",
		labelURL: "URL",
		mymyAccount: "mymy 계정",
		placeholder_Email: "mymy 계정을 입력해주세요.",
		member: "회원",
		guest: "게스트(조회만 가능)",
		permissions: "사용자 권한",
		copyLink: "링크 복사",
		subContent: "콘텐츠 조회 및 댓글 달기, 업로드와 다운로드가 가능합니다.",
		enterName: "커뮤니티 이름을 입력해주세요.",
		title_1: "커뮤니티를 만들어 아카이브에 있는 사진을 공유해보세요.",
		file_upload: "업로드",
		invite: "초대",
		upload: "미디어 업로드",
		invitation: "사용자 초대",
		empty_line_1:
			"MYMY Archive에 보관 중인 사진을 함께 볼 수 있어요. \n커뮤니티에 함께 볼 미디어를 업로드해보세요.",
		empty_line_2: "커뮤니티 회원은 100명까지 초대할 수 있습니다.",
		empty_line_comcat_2:
			"카테고리가 비어있습니다.\n+를 눌러 파일을 추가하세요.",
		account_not_exist: "등록되지 않은 이메일입니다.",
		account_invited_community: "이 계정은 초대되었습니다",
		asset_picking_upload_title: "커뮤니티 업로드",
		create_new_com_cat: "새 카테고리 만들기",
		save_asset_archive_title: "내 아카이브에 저장",
		save_asset_archive_text:
			"선택한 항목을 내 아카이브에 저장하시겠습니까? \n저장된 항목은 <strong style='color: #009BDB'>내 아카이브</strong>에서 볼 수 있습니다.",
		modal: {
			delete_title: "커뮤니티 콘텐츠 삭제",
			content: (nameCommunity) =>
				`선택한 항목을 삭제하시겠습니까?\n <strong style='color: #009BDB'>${nameCommunity}</strong>에 있는 원본 파일은 삭제되지 않습니다.`,
		},
		comment: {
			delete: "댓글 삭제",
			edit: "댓글 수정",
			publisher: "게시자",
			cancel: "취소",
			comment: "댓글",
			enterComment: "댓글 입력",
			delete_title: "댓글 삭제",
			content: "이 댓글을 삭제하시겠습니까?\n 삭제 후에는 복구할 수 없습니다.",
		},
		folder: {
			rename_title: "카테고리 이름 커뮤니티 변경",
		},
		memberList: {
			invite: "초대하기",
			community_member: "커뮤니티 회원",
		},
		moveFolder: {
			move_items: "커뮤니티 카테고리 이동",
		},
		me: "나",
		manager: "관리자",
		epired_community: "유효하지 않은 커뮤니티 정보입니다.",
		copy_link_invite: "커뮤니티 링크가 복사되었습니다.",
		community_upload_popup_empty: "mymy 아카이브가 비어있습니다.",
		community_upload_popup_search_empty: "검색 결과가 없습니다.",
		upload_modal: {
			search_placeholder: "검색어를 입력하세요",
		},
		pageSize: "개씩 보기",
		no_community: "아직 생성된 커뮤니티가 없습니다.",
	},
	my_community_setting: {
		leave_title: "커뮤니티 탈퇴",
		leave_content: (name) =>
			`<span  class="leave-community-title">커뮤니티를  탈퇴하시면</span> \n <li>해당 커뮤니티에 접속하실 수 없습니다.</li><li><span class="highlight" style="color:#009BDB;word-break: break-word;">${name}</span>님이 올린 미디어는 모두 삭제되지만 댓글은 삭제되지 않습니다.</li>`,
		confirm_leave: "커뮤니티 탈퇴에 따르는 사항을 확인했습니다.",
		joining_date: "커뮤니티 가입",
		permissions_access: "커뮤니티 권한",
		permissions_status_member: "회원",
		permissions_status_guest: "손님",
		permissions_status_owner: "소유자",
		close_title: "커뮤니티 닫기",
		close_community_btn: "커뮤니티 폐쇄",
		close_content: (communityName) =>
			`<span  class="leave-community-title">커뮤니티를  폐쇄하시면 </span><li>폐쇄 절차가 완료됨과 동시에 커뮤니티가 폐쇄됩니다. </li><li><span class="highlight" style="color:#009BDB;word-break: break-word;">${communityName}</span>에 있는 모든 미디어와 댓글들이 삭제되어 복구할 수 없습니다. \n<span style="margin-left:24px">폐쇄 전에 커뮤니티 회원들에게 폐쇄를 고지해 미디어를 백업하세요.</span></li>`,
		confirm_close: "커뮤니티 폐쇄에 대해 다음 사항을 확인했습니다.",
		close_notice: "커뮤니티가 닫힙니다",
		password: "비밀번호",
		enter_password: "마이마이 계정의 비밀번호를 입력해주세요.",
		leave_btn: "커뮤니티 탈퇴",
		close_btn: "닫다",
		wrong_password: "비밀번호가 일치하지 않습니다. \n다시 확인해주세요.",
		tab_0: "기본 정보",
		tab_1: "나의 콘텐츠",
		tab_2: " 나의 댓글",
		community_setting_tab_0: "커뮤니티 관리",
		community_setting_tab_1: "커뮤니티 사용량",
		community_setting_tab_2: "회원 관리",
		delete_btn: "선택한 댓글 삭제",
		delete_alert_title: "커뮤니티 댓글 삭제",
		delete_alert_content:
			"선택한 댓글을 삭제하시겠습니까? \n삭제한 댓글은 복구할 수 없습니다.",
		comment: "댓글",
		title: "제목",
		category: "카테고리",
		comment_date: "작성 일시",
		displayCommunityName: "커뮤니티 이름",
		community_open_date: "커뮤니티 가입",
		community_status: "커뮤니티 상태",
		community_cell_0: "회원 이름",
		community_cell_1: "상태",
		community_cell_2: "가입일",
		community_cell_3: "최종 방문일",
		community_cell_4: "권한",
		modify_permission: "커뮤니티 권한 수정",
		modify_permission_alert: (children) =>
			`‘<span style="color:#009BDB;word-break: break-word;font-weight: 500;">${children}</span>’의 권한을 수정하시겠습니까?`,
		status_on: "운영",
		status_pause: "일시정지",
		permission_member: "회원",
		permission_guest: "게스트",
		invite_member: "초대하기",
		people: "명",
		community_member_expel_title: "커뮤니티 회원 탈퇴",
		community_member_expel_alert: (name) =>
			`<span class="highlight" style="color:#009BDB;word-break: break-word;">${name}</span>님을 탈퇴시키시겠습니까?\n탈퇴된 회원이 올린 미디어와 댓글은 삭제되지 않습니다.`,
		cancel_invitation_title: "커뮤니티 초대 취소",
		cancel_invitation_alert: (name) =>
			`<span class="highlight" style="color:#009BDB;word-break: break-word;">${name}</span>님 초대를 취소하시겠습니까?`,
		expel_btn: "탈퇴",
		cancel_invitation_btn: "초대 취소",
		my_community: "내 활동 관리",
		community_settings: "커뮤니티 설정",
		leave_community_toast: "커뮤니티를 탈퇴했습니다.",
		status_joined: "합류",
		status_reject: "거부하다",
		status_waiting: "대기 중",
		alert_delete_community_content_title: "커뮤니티 콘텐츠 삭제",
		alert_delete_community_content: (folder) =>
			`선택한 항목을 삭제하시겠습니까? \n<span class="highlight lineheight">${folder}</span>에 있는 원본 파일은 삭제되지 않습니다.`,
		question_mark:
			"일시정지 된 커뮤니티는 관리자를 제외한 \n회원들의 접속이 제한됩니다.",
		change_setting_btn: "커뮤니티 설정 변경",
	},
	_button: {
		accept: "승인",
		add_new: "새로 추가",
		add_permission: "권한 등록",
		add: "등록",
		backup: "백업",
		cancel: "취소",
		cancellation: "취소",
		check_duplicate_email: "이메일 중복확인",
		close_community: "커뮤니티 닫기",
		close: "닫기",
		create: "저장",
		delete_approval: "삭제 승인",
		delete_community: "커뮤니티 삭제",
		delete_history: "이력 삭제",
		delete_permission: "권한 삭제",
		delete_rejected: "삭제 반려",
		delete: "삭제",
		edit: "편집",
		exit: "출구",
		go_to_original: "원본으로 이동",
		login: "로그인",
		move: "이동",
		pause: "일시정지",
		refresh: "새로 고침",
		reject_deletion: "반려",
		reject: "거절",
		reset_email: "인증 메일 초기화",
		reset_filter: "검색 초기화",
		reset_password: "비밀번호 초기화",
		save: "저장",
		search: "검색",
		signin: "회원가입",
	},
	login: {
		policy_text: `이 사이트는 reCAPTCHA에 의해 보호되며 Google <a href="https://policies.google.com/privacy">개인정보 보호정책</a> 및 <a href="https://policies.google.com/terms">이용 약관</a>이 적용됩니다.`,
		or: "또는",
	},
};
