export default {
	language_code: "en",
	general: {
		add: "Add",
		alarm: "Alarm",
		all: "All",
		apply: "Apply",
		audios: "Audios",
		back: "Back",
		cancel_popup: "Close",
		cancel: "Cancel",
		check: "Check",
		close: "Close",
		confirm_delete: "Confirm Delete",
		confirm: "Confirm",
		create: "Create",
		createv2: "Create",
		day: "Day",
		delete_all_forever: "Delete",
		delete_all_trash: "Empty trash",
		delete_all: "Delete all",
		delete: "Delete",
		disable_2: "Disable",
		disable: "Disable",
		done: "Done",
		download: "Download",
		edit: "Edit",
		empty_items: "No data",
		enable_2: "Enable",
		enable: "Enable",
		expand: "Expand",
		from: "From",
		go: "Go",
		high: "High(original)",
		images: "Images",
		load_theme: "Loading theme ...",
		loaded: "Loaded",
		loading: "Loading",
		low: "Low",
		modify: "Modify",
		month_1: "January",
		month_10: "October",
		month_11: "November",
		month_12: "December",
		month_2: "February",
		month_3: "March",
		month_4: "April",
		month_5: "May",
		month_6: "June",
		month_7: "July",
		month_8: "August",
		month_9: "September",
		month: "Month",
		move: "Move",
		no_data: "No data",
		no_name: "No name",
		no: "No",
		none: "None",
		notice: "Notice",
		notification: "Notification",
		ok: "OK",
		pause: "Pause",
		photos: "Photos",
		refresh: "Clear",
		registration: "Registration",
		reset_all: "Reset All",
		reset: "Reset",
		restore_all_trash: "Restore All",
		restore_all: "Restore",
		save: "Save",
		search_placeholder: "Search images & videos",
		search: "Search",
		select_opt: "Select options ...",
		select: "Select",
		selected_2: " Selected",
		selected: "Selected",
		share: "Share",
		standard: "Standard",
		text_delete: "Are you sure you want to delete",
		text_time_out: "is over.",
		timeout: "Timeout",
		to: "To",
		videos: "Videos",
		viewmore: "More",
		year: "Year",
		yes_popup: "Yes",
		yes: "Yes",
		id_duplicate: "Check",
		email_duplicate: "Check",
	},
	alert: {
		error: "Error",
		warning: "Warning!",
		notice: "Notice",
		success: "Success!",
		confirm: "Confirm",
		alert: "Alert",
		appInfo:
			"Can not get the app name, please reload the page or try again later!",
		login_non_exist_email: "This is an unregistered account.",
		login_wrong_password: "The account information you entered does not match.",
		unactivated_user: "Please wait for the admin’s approval.",
		loginFailTimeHandle: (time) =>
			`The account information you entered does not match. (<span style="color:#009BDB">${time}</span>/5 times)\nLogin is restricted after 5 consecutive errors.`,
		login_1: "Account does not exist!",
		login_2: "Something is wrong, please try again later!",
		login_3: "Email information not found!",
		login_4:
			"You have registered successfully, please check your email to confirm your account!",
		login_5:
			"Please check your email to receive new password! Then login again.",
		login_6: "Wrong password",
		login_7:
			"Account verification is required.\n Please check your mailbox to verify the account before you sign in.",
		login_8:
			"This is an unverified email.\n Please check your mailbox and verify it.",
		register_1: "Registered email",
		register_exists: "Email already exists",
		register_2: "This login name is already registered",
		register_3: "This phone is already registered",
		register_4: "Resend email success! \n Please check your email again.",
		id_exists: "Registered ID",
		storage_1:
			"Can't get storage assignments, please reload the page or try again later!",
		storage_2:
			"Can't create storage assignments, please reload the page or try again later!",
		ingest_1:
			"Can't get ingest configs, please reload the page or try again later!",
		ingest_2:
			"Can't create ingest config, please reload the page or try again later!",
		outgest_1:
			"Can't get outgest configs, please reload the page or try again later!",
		outgest_2:
			"Can't create outgest config, please reload the page or try again later!",
		task_1:
			"Cannot get the service, please download back page or try again after",
		task_2:
			"Cannot create an service, please download back page or try again after",
		audioassets_1:
			"Can't get audio of asset, please reload the page or try again later!",
		audioassets_2:
			"Can't create audio of asset, please reload the page or try again later!",
		cat_1: "Can't get categories, please reload the page or try again later!",
		cat_2:
			"Can't create categories, please reload the page or try again later!",
		cat_3:
			"Can't rename categories, please reload the page or try again later!",
		cat_4:
			"Can't delete categories, please reload the page or try again later!",
		cat_5: "Can't move categories, please reload the page or try again later!",
		com_accept:
			"Can't Accept this Community, please reload the page or try again later!",
		com_create_1:
			"Can't Create Community, please reload the page or try again later!",
		com_edit_1:
			"Can't Edit Community, please reload the page or try again later!",
		com_invite_1:
			"Can't Invite User to Community, please reload the page or try again later!",
		com_invite_url_exp:
			"The link has expired, you can't join the community, please try again with a new link!",
		com_invite_url_invalid:
			"The link has invalid, you can't join the community, please try again with a new link!",
		com_invite_already_a_member: "You have already joined.",
		com_invite_url_unknown:
			"The link has unknown, you can't join the community, please try again with a new link!",
		com_invite_2: "You are already invited.",
		tag_1:
			"Can't get tag color and name, please reload the page or try again later!",
		tag_2: "Can't add new tag, please reload the page or try again later!",
		tag_3: "Can't edit tag, please reload the page or try again later!",
		tag_4: "Can't delete tag, please reload the page or try again later!",
		sto_1: "Can't get storage used, please reload the page or try again later!",
		img_1: "Can't get list images, please reload the page or try again later!",
		img_2:
			"Can't add tag for this image now, please reload the page or try again later!",
		img_3:
			"Can't remove tag for this image now, please reload the page or try again later!",
		img_4:
			"Can't perform this action right now, please reload the page or try again later!",
		time_1: "Can't get timeline, please reload the page or try again later!",
		pro_1:
			"Can't get profile's information, please reload the page or try again later!",
		pro_2:
			"Cannot change the password.\nPlease check the password you entered.",
		pro_3:
			"Can't send your request to server, please reload the page or try again later!",
		up_1: "Failed – unsupported formats",
		up_2: "The file is too large! you can only upload file lower 500mb.",
		up_3: "The file is duplicated and it has been skipped!",
		up_4: "This image url is blocked by the server itself. Please try another one!",
		up_5: "File uploaded fail",
		up_6: "Get image size fail",
		up_video:
			"The file is too large! you can only upload video file lower 4GB.",
		up_audio:
			"The file is too large! you can only upload audio file lower 4GB.",
		up_image:
			"The file is too large! you can only upload image file lower 200MB.",
		up_document:
			"The file is too large! you can only upload document file lower 500MB.",
		up_model:
			"The file is too large! you can only upload model file lower 500MB.",
		up_other: "The file is too large! you can only upload file lower 500MB.",
		up_size_0: "File has size 0 or file is corrupted.",
		face_1:
			"Can't get list of faces, please reload the page or try again later!",
		face_2:
			"Can't delete this face now, please reload the page or try again later!",
		face_3: "Can't upload face from this image to server!",
		download_failed: "Can't download image due to error",
		major_face:
			"This face can't be deleted because it's a major face for this person",
		upload_progress_exist:
			"Upload is in progress. \n Please complete the previous upload to continue.",
		delete_narration_title: "Delete Narration",
		delete_narration_text:
			"Are you sure you want to delete '{value}'?\nDeleted narration cannot be restored.",
		delete_narration_text2:
			"Are you sure you want to delete the selected narration?\nDeleted narration cannot be restored.",
		success_count: "{value} Success",
		failure_count: "{value} Failure",
		permission_microphone:
			"Please allow mic permission \nfor recording narration.",
		empty_search_value: "Please enter a search term.",
		login_fail_alert:
			"The account information you entered does not match. \nLogin is restricted after 5 consecutive errors.",
		login_restriction:
			"Login was restricted due to an error in entering account information 5 times in a row.\nPlease log in after resetting your password.",
		login_reset_password: "Reset password",
		times: " times",
		login_error: "Login Error",
		community_pause:
			"Community has been paused by admins so you can't access the community",
		change_password_content_1: "Update successfully.",
		change_password_content_2:
			"Cannot change your password.\nPlease check the information you entered.",
		update_category_order: "Category order has changed.",
	},
	topmenu: {
		config: "Management",
		profile: "Personal Information",
		logout: "Logout",
		admin_dashboard: "Managerment",
		upload: "Upload",
		theme: "Theme",
		language: "Language",
		listFace: "Face",
		faceSearch: "Search by Face",
		noFaceFound: "No faces found!",
		location: "Location",
		pickLocation: "Pick a location...",
		searchLocation: "Search location",
		noResultFound: "No result found",
		noPermission: "No permission to access location",
		profile_setting: "Profile setting",
		language_setting: "Languages",
		dark_mode: "Dark mode",
		light_mode: "Light mode",
		search_for_place: "Search for a place",
		setting: "User Setting",
	},
	categories: {
		my_drive: "My Archive",
		public: "Public",
		community: "Community",
		trash: "Trash",
		filter: "Filter",
		category: "Category",
		image_format: "Media Format",
		size: "Size",
		share: "Sharing",
		upload_date: "Upload Date",
		tag_color: "Tag Color",
		storage: "Storage",
		remove_tag_filter: "Remove Tag Filter",
		large: "Large (>10MB)",
		large_2: "Large",
		medium: "Medium (1~10MB)",
		medium_2: "Medium",
		small: "Small (<1MB)",
		small_2: "Small",
		custom_size: "Custom size",
		ratio: "Ratio",
		quality: "Quality",
		tall: "Tall",
		wide: "Wide",
		square: "Square",
		quality_high: "High",
		quality_high_tooltip: "- Length or height greater than 1920px",
		quality_medium: "Medium",
		quality_medium_tooltip: "- Length or height between 512 and 1920px",
		quality_low: "Low",
		quality_low_tooltip: "- 512 pixels or less in length or height",
		today: "Today",
		last_week: "Last week",
		last_month: "Last month",
		direct_input: "Direct input",
		file_format: "File Formats",
		period: "Period",
	},
	tag: {
		empty_tag: "There's no tags yet!",
		contain_all: "This image are containing all tags!",
		remove_tag: "Remove Tags",
		add_tag: "Add Tags",
		index: "Index",
		name: "Name",
		color: "Color",
		title_custom: "Custom Tags",
		title_edit: "Edit Tag",
		title_add: "Add Tag",
		tag_name: "Tag's Name",
		tag_color: "Tag's Color",
		title_error: "Title must be between 1 and 64 characters!",
	},
	preview: {
		guide_text:
			"Select an image for the preview. Hold <kbd>Ctrl</kbd> or <kbd>Shift</kbd> to select multiple images.",
		more_detail: "Open detail",
	},
	metadata: {
		meta_title: "Metadata",
		file_meta_title: "File Metadata",
		files: "File",
		file_extension: "File Extension",
		size: "Size",
		mime_type: "MIME Type",
		resolution: "Resolution",
		audio_bitrate: "Audio Bitrate",
		audio_channel: "Audio Channel",
		audio_codec: "Audio Codec",
		video_bitrate: "Video Bitrate",
		video_codec: "Video Codec",
		video_frameRate: "Video FrameRate",
		video_resolution: "Video Resolution",
		created_date : "Created Date",
 		last_modified : "Last Modified Date",
		duration : "Length",
		metadata: "Metadata",
		custom_metadata: "Custom Metadata",
		software: "Software",
		number: "Number",
		iso: "ISO Speed Ratings",
		title: "Title",
		desc: "Description",
		position: "Coordinate",
		location: "Category",
		narrations: "Narration",
		upload_date: "Upload Date",
		last_modified_date: "Last Modified Date",
		creation_date: "Creation date",
		creator: "Creator",
		exif: {
			exifDateTimeOriginal: "Date Time Original",
			exifMake: "Make",
			exifModel: "Camera Model Name",
			exifFocalLength: "Focal Length",
			exifFNumber: "F Number",
			exifISO: "ISO",
			exifExposureTime: "Exposure Time",
			exifExposureProgram: "Exposure Program",
			exifFlash: "Flash",
			exifGPSLatitude: "GPS Latitude",
			exifGPSLongitude: "GPS GPSLongitude",
			exifOrientation: "Orientation",
			exifModifyDate: "Modify Date",
			exifDataTimeDigitized: "Data Time Digitized",
			exifColorSpace: "Color Space",
			exifMeteringMode: "Metering Mode",
			exifPixelXDimension: "Pixel X Dimension",
			exifPixelYDimension: "Pixel Y Dimension",
			exifExposureBiasValue: "Exposure Bias Value",
			exifMaxApertureValue: "Max Aperture Value",
			exifSoftware: "Software",
			exifLightSource: "Light Source",
			exifImageDescription: "Image Description",
			exifExifVersion: "Exif Version",
			exifUserComment: "User Comment",
			exifComponentsConfiguration: "Components Configuration",
			exifCompressedBitsPerPixel: "Compressed Bits Per Pixel",
		},
		string: "String",
		text: "Text",
		string_options: "String options",
		list: "List",
		date: "Date",
		option: "Option",
	},
	status: {
		all: "All",
		completed: "Completed",
		failed: "Failed",
	},
	filter_tool: {
		period: "Period",
		status: "Status",
		mediaType: "Media type",
		category: "Category",
		search: "Search",
		archive: "My archives",
		selectF: "Select folder",
		title: "Title",
		fileName: "File name",
	},
	folder: {
		create_folder: "Create category",
		create_folder_community: "Create a community category",
		create_inside: "Create new category under",
		root_folder: "Root category",
		enter_name: "Enter category name",
		name_error: "Category name must be between 1 - 128 characters!",
		name_Category_error: "Category name must be between 1-128 characters.",
		name_community_error: "Community name must be between 1-128 characters.",
		move_folder: "Move category",
		current_folder: "Current category",
		move_to: "Move category",
		share_to: "Share",
		choose_folder: "Choose new category to move in",
		rename_title: "Rename category",
		delete_folder: "Delete category",
		restore_folder: "Restore category",
		delete_text_1:
			"You need to delete all sub-category and images contain inside this category first!",
		delete_text_2: "Are you sure you want to delete {value}",
		delete_text_3:
			"Are you sure you want to delete {value} and all items inside ? This will delete permanently and cannot undo.",
		add_new_folder: "Add new category",
		same_id_err:
			"Current category is same as target category, please choose another one!",
		restore_text_1: "Do you want to restore {value} and all assets inside ?",
		category: "Category",
		location: "Location",
		creating_folders: "Creating categories, please wait...",
		move_to_trash_title: "Move to Trash",
		move_to_trash_text:
			"Do you want to move selected items to Trash? Moved items can be restored from Trash",
	},
	imageLayout: {
		subfolder: "Subfolder",
		choose_items: "Select category",
		empty: "no data",
		restore: "Restore",
		restore_selected_item: "Do you want to restore selected items?",
		text_restore: "Do you want to restore {value}",
		text_restore_2: "Do you want to restore all items?",
		delete: "Confirm Delete ?",
		text_delete_1:
			"{value} will be permanently deleted, do you want to continue ?",
		text_delete_3:
			"Put all items to Trash? You can recover them in Trash later!",
		text_delete_4: "Permanently delete all items? You cannot undo this action!",
		trash: "Move to Trash ?",
		text_trash_1: "Move {value} to Trash ? You can recover it in Trash later.",
		move_to_trash_title: "Move to Trash",
		move_to_trash_text:
			"Do you want to move selected items to Trash? Moved items can be restored from Trash",
		thumbnail: "Thumbnail",
		name: "Name",
		tag: "Tag",
		resolution: "Resolution",
		created_day: "Created Day",
		size: "Size",
		updated_day: "Last Updated",
		no_img: "Images not available!",
		latest: "Latest",
		earliest: "Earliest",
		a_z: "Name A-Z",
		z_a: "Name Z-A",
		shooting_date: "Shooting Date",
		last_most_day: "Last Modified Date",
		reg_date: "Registration Date",
		title: "Title",
		selected_items: "asset(s)",
		selected_folders: "category(s)",
		drop_img: "Drop Images/Folders here to upload to current category",
		drop_img1: "Drop files/folders or click here to upload...",
		drop_img2: [
			"Image (png, jpeg, gif, webp, svg, bmp, avif, tiff, ...)",
			"Audio (mpeg, wave, wav, mp3, ...)",
			"Video (mp4, mjpeg, mov, web, avi, ...)",
			"Document (pdf, docx, ppt, text, html, ...)",
		],
		upload_title: "Upload Media",
		uploading: "Uploading files",
		upload_complete: "Files upload completed",
		upload_failed: "Files upload failed",
		uploaded: "Uploaded!",
		canceled: "Canceled",
		failed_canceled: "Failed - canceled",
		failed: "Failed!",
		goto_upload_location: "Go to upload location",
		cancel_upload: "Cancel upload",
		continue_upload: "Continue upload",
		stay: "Stay",
		leave: "Leave",
		retry_upload: "Retry",
		stop_upload: "Stop",
		resume_upload: "Resume",
		enterUrl: "URL upload",
		enterUrlImg: "Enter URL of image",
		upload: "Upload",
		timeline: "Timeline",
		alphabet: "Alphabet",
		most_similar: "Most Similar",
		toggle_timeline: "Toggle timeline mode",
		warning: "Warning",
		text_warning_max: "The amount of audio has reached the limit 3",
		add_a_title: "Add a title",
		add_a_desc: "Add a description",
		add_a_value: "Add a value",
		faces: "Faces",
		audio_desc: "Audio description",
		origin_name: "Original name",
		showSubFile: "Show all Sub-files",
		move_items: "Move items",
		share_items: "Share items",
		select_items: "Select folder",
		location: "Location",
		current_location: "Current Location",
		move_location: "Move Location",
		multi_location: "Multi Location",
		move_folder_guide: "Please select the category to move.",
		move_folder_guide_2: "Choose a category to view.",
		move_folder_guide_3: "Choose a community to share with.",
		no_folder_1: "There are no categories that can be moved.",
		no_folder_2:
			"Please create a category to move through the Add New Category button.",
		compress_file: "Compressed files",
		separate_file: "Individual files",
		download_alert:
			"You have selected {value} images.\n Do you want to download?",
		download_limit_title: "Notice",
		download_limit: "You can download up to 300 files.",
		download_limit_confirm: "Confirm",
		upload_file_invalid:
			"Files are invalid or empty! You can only choose image, video or audio file type.",
		prepare_upload: "Preparing upload, please wait...",
		subcategory: "Sub-Category",
		empty_asset: "The category is empty. \nClick + to add a file.",
		empty_trash: "Empty Trash.",
		empty_search: "No search result",
		selected_items_mobile: "selected",
		empty_asset_desktop_1: "The mymy archive is empty.",
		empty_asset_desktop_2:
			"Drag and drop files or folders here or click the Upload button.",
		empty_community_desktop_1:
			"You can view photos stored in MYMY Archive together. \n  Upload media to watch with the community.",
		empty_community_desktop_2: "Community members can invite up to 100 people.",
		waiting_community_desktop_1:
			"You can view photos stored in MYMY Archive together.",
		waiting_community_desktop_2: "Upload media to watch with the community.",
		file_upload: "Upload file",
		file_upload_2: "Upload file",
		url_upload_guide: "Upload an image by copying the {value} of the image.",
		url_upload_guide_2: "Upload an image by copying the {value} of the image.",
		title_notice: "Notice",
		title_alert: "Alert",
		content_notice: "Are you sure you want to cancel the upload?",
		content_notice2:
			"Are you sure you want to leave the page? \n Uploads in progress may be canceled.",
		trash_info: `Items in the trash are completely \n deleted after 90 days.`,
		trash_info2: `Items in the trash are completely deleted after approval of admin.`,
		fail_image_content_1: "Could not load image.",
		fail_image_content_2: "Error loading image.",
		fail_audio_content_1: "Could not load audio image.",
		fail_audio_content_2: "Error loading image.",
		fail_video_content_1: "Could not load video.",
		fail_video_content_2: "Error loading video.",
		fail_document_content_1: "Could not load document.",
		fail_document_content_2: "Error loading document.",
		audio_image_edit: "Audio image edit",
	},
	contextMenu: {
		view: "View Image",
		restore_title: "Restore",
		restore_text: "Do you want to restore selected items?",
		edit: "Edit Metadata",
		move: "Move category",
		delete: "Delete",
		delete_forever_title: "Delete permanently",
		delete_forever_text:
			"Are you sure to delete selected items? \n Deleted items cannot be restored",
		delete_forever_text2: "Are you sure you want to delete the selected item?",
		delete_all_title: "Delete all",
		delete_all_text:
			"Are you sure to delete all items in the trash? \n Deleted items cannot be restored.",
		delete_category_title: "Delete Category",
		delete_category_text:
			"Are you sure to delete this category?\n Deleted items cannot be recovered",
		request_delete_category_title: "Request delete to admin",
		request_delete_category_text:
			"Are you sure you want to submit a request to delete this category?\n Your request will be sent to admin",
		request_delete_assets_title: "Request delete to admin",
		request_delete_assets_text:
			"Are you sure you want to submit a request to delete this assets?\n Your request will be sent to admin",
		request_delete_assets_text2:
			"Are you sure you want to delete the selected item?",
		request_delete_list_file_title: "Request delete to admin",
		request_delete_list_file_text:
			"Are you sure you want to submit a request to delete this list file?\n Your request will be sent to admin",
		warning_permission: "Permission warning",
		warning_permission_text:
			"Do not have permission to delete categories or delete assets. Please select items again.",
		reselect: "Reselect",
		send_request: "Send request",
		restore_all_title: "Restore all",
		restore_all_text: "Do you want to restore all items?",
		download_thumb: "Download thumbnail",
		download_full: "Download full size",
		new_folder: "New category",
		rename: "Rename",
		move_folder: "Move category",
	},
	detailAsset: {
		desc_error: "Length of description must be less than 300 characters",
		title_error: "Length of title must be in 1 - 256 characters",
		share: "Share",
		hide_info: "Hide information",
		copied: "Copied!",
		find_in_mymy: "Upload Audio Image",
		find_on_my_device: "Find on my device",
		upload_cover_btn: "Upload",
	},
	profile: {
		cancel_description: "Delete your account",
		change_email: "Change email",
		change_info: "Change information",
		change_password: "Change password",
		col_custom: "Columns list",
		daily_traffic: "Daily Traffic",
		day_exp1: "DD (Example: 01)",
		day_exp2: "DD Day (Example: 01 Day)",
		day_exp3: "Day DD (Example: Day 01)",
		day_format: "Day style",
		delete_info: "Delete Account",
		department_placeholder: "Please enter the department name.",
		displayName: "Name",
		download: "Download",
		email_verify_1: "Your email is not verified!",
		email_verify_2: "Please check your email to confirm!",
		email_verify_3: "Verify now",
		email: "Email",
		enter_new_password: "Enter your new password",
		enter_old_password: "Please enter your current password",
		firstName: "First name",
		folder: "Categories",
		forgot: "Forgot Password",
		get_password: "Get New Password",
		goto_change_password: "Change password",
		help: "Help",
		image: "Images",
		in_use: "In use",
		join_in: "Sign up",
		lastName: "Last name",
		login_page: "Login Page",
		login: "Login",
		loginName: "Login name",
		mess_error_email: "Invalid email!",
		mess_error_firstName: "First name must be between 4 ~ 64 characters.",
		mess_error_lastName: "Last name must be between 4 ~ 64 characters.",
		mess_error_loginName:
			"Name does not contain space or special characters and must be between 4 ~ 18 characters",
		mess_error_password:
			"Password does not contain space and must be between 4 ~ 64 characters",
		mess_error_phone:
			"Phone number can't contain characters and must be between 10 ~ 20 digits",
		mess_error_rePassword: "Confirm password does not the same as password!",
		mobilePhone: "Mobile phone",
		month_exp1: "MM (Example: 01)",
		month_exp2: "mmm (Example: Jan)",
		month_exp3: "MMM (Example: JAN)",
		month_exp4: "mmmm (Example: January)",
		month_exp5: "Month MM (Example: Month 01)",
		month_exp6: "MM Month (Example: 01 Month)",
		month_format: "Month style",
		my_gallery: "My Gallery",
		newPassword: "New password",
		next: "Next",
		notice_1: "Your subscription cancellation is complete.",
		notice_2: "Please check your password.",
		notice_success_changepass: "You have successfully changed your password",
		oldPassword: "Current password",
		or: "or",
		password: "Password",
		phone_number_placeholder: "Please enter your phone number.",
		reason: "Why do you want to delete your account?",
		register: "Join in",
		rePassword: "Confirm password",
		reset_email_text:
			"There is a registered e-mail address. \nDo you want to reset the registered e-mail information?",
		reset_email_title: "Reset Email",
		reset_email: "Reset Email",
		return_dashboard: "Return to My Archive",
		save_community_info: "Change information in community",
		save_info: "Save information",
		tab_menu_0: "Account Information",
		tab_menu_1: "Email",
		tab_menu_2: "Change Password",
		tab_menu_3: "Statistics",
		tab_menu_delete_Account: "Delete your account",
		tag: "Tags",
		timeline_format: "Timeline format",
		total: "Total",
		update_success: "Update successfully!",
		update_success2: "Update successfully",
		usage_storage: "Usage Storage",
		used: "Used",
		user_statistic: "User Statistic",
		wrong_password: "Wrong password",
		year_exp1: "YYYY (Example: 2021)",
		year_exp2: "Year YYYY (Example: Year 2021)",
		year_exp3: "YYYY Year (Example: 2021 Year)",
		year_format: "Year style",
	},
	landing: {
		banner_title: "Keep your precious images safe!",
		banner_subtitle:
			"MYMY Archive helps you to keep your images safe both online & offline \nand to navigate them quickly anytime you want",
		banner_subtitle_mobile:
			"MYMY Archive helps you to keep your images safe both online & offline and to navigate them quickly anytime you want",
		join_in: "Join in",
		already_a_member: "Already a member?",
		login: "Login",
		box_1_title: "Always safe & secured",
		box_1_description:
			"Safely save your images and access them on PC, smartphone, and more",
		box_2_title: "Add descriptions",
		box_2_description: "Simply add descriptions using voice and text",
		box_3_title: "Quick navigation",
		box_3_description:
			"Quickly find your images using faces, places, dates, or keywords",
		box_4_title: "Easy sharing",
		box_4_description:
			"Easily share your images with friends and family through SNS",
		address: "08380) RM 408, 11 Digital-ro 33gil, Guro-gu, Seoul, Korea",
		phone_1: "+82-2-857-1101",
		phone_2: "+82-2-2025-7444",
		res_title: "Fully responsive",
		res_text: "Scales to any device for flexible access",
		per_title: "Great Performance",
		per_text: "Built on the experience of years with Ariel MAM.",
		awe_title: "Awesome User Experience",
		awe_text: "Modern interface that is a breeze to navigate",
		mobile_title: "SLEEK - EASY - MOBILE",
		mobile_text:
			"GIMA dashboard is your one-stop-shop for quick access to all your essential digital assets.",
		contact_title: "CONTACT US",
		contact_text:
			"We're here to answer all your questions! Feel free to drop us a line any time.",
		id: "ID",
		rmb_id: "Remember ID",
		enter_id: "Enter your ID",
		find_by_id: "Find by ID",
		empty_id: "Please enter your ID.",
		invalid_id: "Invalid ID.",
		short_id: "Invalid ID must be at least 4 characters.",
		long_id: "Please enter up to 128 characters.",
		id_error_text_length: "Enter between 4 and 20 characters.",
		id_error_text_english: "Only English and numbers within 20 characters are allowed.​",
		registered_id: "Registered ID.",
		department: "Department",
		enter_department: "Enter department",
		mobile_number: "Mobile number",
		enter_mobile_number: "Enter mobile number",
		phone_number: "Phone number",
		enter_phone_number: "Enter phone number",
		email: "Email",
		password: "Password",
		rmb_email: "Remember email",
		rmb_auth: "Stay signed in",
		forgot_password: "Forgot your account information? {value}",
		click_here: "Click here",
		name: "Name",
		rePassword: "Confirm password",
		phone: "Phone",
		verify_phone: "Verify",
		enter_email: "Enter your email",
		enter_name: "Enter login name",
		enter_password: "Enter password",
		enter_rePassword: "Re-type your password",
		enter_phone: "Phone number",
		term_confirm:
			"I agree to the terms of use, collection and use of personal information",
		signup_complete: "Sign up complete",
		find_account: "Find an account",
		find_password: "Find Password",
		find_by_email: "Find by email",
		forgot_password_title: "Forgot password",
		request_by_admin: "Request administrator reset",
		request_by_admin_title: "Administrator reset",
		find_by_phone: "Find by phone number",
		reset_via_email: "You can reset your password via email.",
		receive_password: "Receive password",
		request_to_admin: "Send request to admin",
		empty_email: "Please enter your email.",
		empty_password: "Please enter your password.",
		invalid_email: "Invalid email.",
		invalid_password: "Invalid password",
		invalid_rePassword: "Password mismatch",
		invalid_department: "Please enter up to 128 characters.",
		invalid_name: "Please enter within 2-32 characters.",
		invalid_phone: "Invalid phone number",
		short_password: "Password must be at least 4 characters",
		invalid_notice:
			"Account verification mail is sent. \n Please check your mailbox",
		resend_email: "Resend",
		account_verify: "Verify your account",
		account_verify_text:
			"A verification email has been sent to\n{value}\nPlease check your mailbox to verify the account before you sign in.",
		account_verify_text_2:
			"Account verification is required. Please check your mailbox to verify the account before you sign in.",
		notice: "Notice",
		invalid_password_1: "Please enter between 8 and 64 characters.",
		invalid_password_2:
			"Password must be between 8-64 and contain at least three of the following: Upper/lowercase letters, numbers, and symbols.",
		invalid_password_3:
			"Password must contain at least three of the following: Upper/lowercase letters, numbers, and symbols.",
		invalid_password_4: "The password is the same as the old password.",
		policy_text: `This site is protected by reCAPTCHA and the Google \n<a href="https://policies.google.com/privacy">Privacy Policy</a> and <a href="https://policies.google.com/terms">Terms of Service</a> apply.`,
		invalid_mobile_phone: "Please enter up to 20 characters.",
		admin_approval_alert:
			"The signup process will be completed \nafter the admin’s approval.",
		title_alert: "Alert",
		id_can_use: "This ID that can be used.",
		id_cannot_use: "This ID that can not be used.",
		email_can_use: "This email that can be used.",
		email_cannot_use: "This email that can not be used.",
		register: "register",
	},
	account: {
		tab_delete_1: {
			title: "Please confirm the account you want to delete",
			content_1:
				"• You can not use 'MYMY Archive' service with the deleted account",
			content_2:
				"• All of your account information and media are permanently deleted and cannot be recovered. Please back up your media before deleting your account.",
			label: "Why do you want to delete your account?",
			reason_Content: "Please enter a reason(at least 10 characters)",
		},
		tab_delete_2: {
			title: "Please confirm the account you want to delete",
			content_1:
				"- You can not use 'MYMY Archive' service with the deleted account",
			content_2:
				"- All of your account information and media are permanently deleted and cannot be recovered. Please back up your media before deleting your account.",
			confirm:
				"I confirm and agree to the process to permanently delete my account information and media.",
			delete_account: "Delete Account",
			enter_password: "Please enter your password",
		},
		reason_0: "Not useful",
		reason_1: "Use another service that is similar to MYMY",
		reason_2: "My account has been hacked",
		reason_3: "Concerned about my privacy and data",
		reason_4: "Don’t know how to use",
		reason_5: "Created a second account",
		reason_6: "Others",
	},
	email_confirm: {
		unvalidate_email: "Unvalidated email!",
		help_request: "Please check your email account or send us a help request.",
		link_expire: "The email verification link has expired.",
		resend_email:
			"Please click the button below to send another verification email.",
		resend_button: "Resend",
		contact_button: "Contact us",
		join_success: "Join-in completed!",
		join_inform: "Welcome! Now everything on MYMY Archive is available.",
		sign_in_button: "Login",
		registered_id: "Registered ID",
	},
	reset_password: {
		title_1: "Change Password",
		title_2: "Set a new password",
		newPassword: "New password",
		rePassword: "Confirm new password",
		placeholder_newPassword: "Enter a new password",
		placeholder_rePassword: "Confirm new password",
		reset_password: "Change",
		invalid_password: "Invalid password",
		invalid_rePassword: "Password mismatch",
	},
	change_password: {
		title_1: "Password change guide",
		title_2: `For privacy protection and safe use of archives We recommend that you change your password every <span class="span">3 months</span>.It is safe to change the password periodically.`,
		oldPassword: "Old password",
		newPassword: "New password",
		rePassword: "Confirm new password",
		placeholder_oldPassword: "Enter your current password",
		placeholder_newPassword: "Enter a new password",
		placeholder_rePassword: "Confirm new password",
		change_password: "Change Password",
		change_later: "Change Later",
		invalid_password: "Invalid password",
		invalid_rePassword: "Password mismatch",
	},
	setting: {
		failed_suport: "Format not supported",
		failed: "Failure",
		success: "Success",
		data_usage: "Date Usage",
		total_usage: "Total Usage",
		title_data_usage: "Total Usage",
		title_metadata: "Metadata Management",
		title_category: "Category Management",
		images: "Images",
		photo: "Photos",
		video: "Videos",
		audio: "Audios",
		metadata_title: "Custom metadata",
		upload_title: "Upload history",
		download_title: "Download history",
		category_title: "Category management",
		metadata_placeholder_opt: "Please enter one or more options",
		face_title: "Face management",
		add: "Register",
		search_placeholder: "Enter your keyword",
		metadata_name: "Metadata Name",
		metadata_type: "Format",
		metadata_active: "Activation",
		create_cmeta_title: "Custom metadata",
		activate: "Activate",
		metadata_format: "Metadata format",
		memo: "Memo",
		enter_memo_placeholder: "Enter note",
		incorrect_title: "Title has at least 1 character",
		incorrect_options: "Empty options",
		alert_delete_metadata_title: "Delete custom metadata",
		alert_delete_metadata:
			"Are you sure you want to delete “{value}”? \n Deleted metadata cannot be recovered.",
		alert_delete_upload_title: "Delete upload history",
		alert_delete_upload:
			"Are you sure you want to delete your history? \n  The original file is not deleted.",
		alert_delete_download_title: "Delete download history",
		alert_delete_title: "Delete history",
		alert_delete_download:
			"Are you sure you want to delete your history? \n  The original file is not deleted.",
		category_name: "Category Name",
		create_date: "Creation Date",
		update_date: "Update Date",
		thumbnail_face: "Face",
		face_name: "Face name",
		find_same_person: "Find the same person",
		related_faces: "Related face person",
		alert_delete: "Are you sure you want to delete “{value}”?",
		major_face: "Representative face",
		title: "Title",
		category: "Category",
		volum: "Volume",
		size: "Size",
		date_download: "Download date",
		date_upload: "Upload date",
		date: "Date",
		status: "Status",
		fileName: "File name",
		boolen_type: "Boolen",
		text_type: "Text",
		date_type: "Date",
		list_type: "List",
		int_type: "Integer",
		decimal_type: "Decimal",
		int_options_type: "Integer Options",
	},
	community: {
		accept: "Getting Started",
		inviteMember: "Community Invite",
		icon: "Community icon",
		create_community: "Create community",
		edit_community: "Edit community",
		inviteByLink: "Invite By Link",
		inviteByAccount: "Invite By Account mymy",
		labelURL: "URL",
		mymyAccount: "mymy Account",
		placeholder_Email: "Please enter mymy account.",
		member: "Member",
		guest: "Guest (view only)",
		permissions: "Permissions Access",
		copyLink: "Copy Link",
		subContent: "you can view, upload/download photos, and leave comments.",
		enterName: "Please enter a community name",
		title_1: "Create a community and share photos from your archive",
		file_upload: "Upload",
		invite: "Invite",
		upload: "Upload",
		invitation: "Invite",
		empty_line_1:
			"You can view photos stored in MYMY Archive together. \nUpload media to watch with the community.",
		empty_line_2: "Community members can invite up to 100 people.",
		empty_line_comcat_2: "Category is empty.\nClick + to add files.",
		account_not_exist: "Unregistered email.",
		account_invited_community: "This account has been invited",
		asset_picking_upload_title: "Community upload",
		create_new_com_cat: "Create a new category",
		save_asset_archive_title: "Save in my archive",
		save_asset_archive_text:
			"Do you want to save selected items in your archive? \nSaved items can be viewed in <strong style='color: #009BDB'>My Archive</strong>.",
		modal: {
			delete_title: "Community content delete",
			content: (nameCommunity) =>
				`Do you want to delete selected items?\nThe original files in <strong style='color: #009BDB'>${nameCommunity}</strong> are not deleted`,
		},
		comment: {
			delete: "Delete",
			edit: "Edit",
			publisher: "Publisher",
			cancel: "Cancel",
			comment: "Comment",
			enterComment: "Enter a comment",
			delete_title: "Delete comment",
			content:
				"Do you want to delete this comment?\n You will not be able to recover after deleting",
		},
		folder: {
			rename_title: "Rename category community",
		},
		memberList: {
			invite: "Invite",
			community_member: "List member",
		},
		moveFolder: {
			move_items: "Move items in community",
		},
		me: "Me",
		manager: "Manager",
		epired_community: "Invalid community information.",
		copy_link_invite: "The community link has been copied.",
		community_upload_popup_empty: "mymy Archive is empty.",
		community_upload_popup_search_empty: "No search results.",
		upload_modal: {
			search_placeholder: "Please enter the search term",
		},
		pageSize: " items",
		no_community: "No community created yet"
	},
	my_community_setting: {
		leave_title: "Leave the community",
		leave_content: (name) =>
			`<span  class="leave-community-title">If you leave the community</span> \n <li>You can not access the community anymore.</li><li>Photos <span class="highlight" style="color:#009BDB;word-break:break-word;">${name}</span> uploaded will be deleted but your comments will not be deleted.</li>`,
		confirm_leave:
			"I have confirmed the following about leaving the community.",
		joining_date: "Joining date",
		permissions_access: "Permissions access",
		permissions_status_member: "Member",
		permissions_status_guest: "Guest",
		permissions_status_owner: "Owner",
		close_title: "Close the community",
		close_community_btn: "Close the community",
		close_content: (communityName) =>
			`<span  class="leave-community-title">If you close the community</span><li>The community will be closed as soon as the process ends.</li><li>All content and comments in <span class="highlight" style="color:#009BDB;word-break:break-word;">${communityName}</span> will be deleted and will not be restored. \n<span style="margin-left:24px">Before the community is closed, notify members to back up the community's content.</span></li>`,
		confirm_close:
			"I have confirmed the following about closing the community.",
		close_notice: "The community is closed",
		password: "Password",
		enter_password: "Enter password",
		leave_btn: "Leave",
		close_btn: "Close",
		wrong_password: "Password mismatch\nPlease check again.",
		tab_0: "Basic info",
		tab_1: "My content",
		tab_2: "My comments",
		community_setting_tab_0: "Community info",
		community_setting_tab_1: "Community usage",
		community_setting_tab_2: "Member management",
		delete_btn: "Delete comments",
		delete_alert_title: "Delete comments",
		delete_alert_content:
			"Do you want to delete selected comments?\nDeleted comments cannot be recovered.",
		comment: "Comment",
		title: "Title",
		category: "Category",
		comment_date: "Comment date",
		displayCommunityName: "Community name",
		community_open_date: "Community open date",
		community_status: "Community status",
		community_cell_0: "Member name",
		community_cell_1: "Status",
		community_cell_2: "Joining date",
		community_cell_3: "Last visited date",
		community_cell_4: "Permission",
		modify_permission: "Edit Community Permissions",
		modify_permission_alert: (children) =>
			`Do you want to modify permissions ‘<span class="highlight" style="color:#009BDB;word-break: break-word;font-weight:500;">${children}</span>’ permissions`,
		status_on: "On",
		status_pause: "Pause",
		permission_member: "Member",
		permission_guest: "Guest",
		invite_member: "Invite",
		people: " People",
		community_member_expel_title: "Community member expel",
		community_member_expel_alert: (name) =>
			`Are you sure you want to expel <span class="highlight" style="color:#009BDB;word-break: break-word;">${name}</span>?\nPhotos and comments from <span class="highlight" style="color:#009BDB">${name}</span> will not be deleted.`,
		cancel_invitation_title: "Cancel invitation",
		cancel_invitation_alert: (name) =>
			`Are you sure  you want to cancel \nYour invitation to <span class="highlight" style="color:#009BDB;word-break: break-word;">${name}</span>?`,
		expel_btn: "Expel",
		cancel_invitation_btn: "Cancel invitation",
		my_community: "My community",
		community_settings: "Community Settings",
		leave_community_toast: "You have left the community.",
		status_joined: "Joined",
		status_reject: "Reject",
		status_waiting: "Waiting",
		alert_delete_community_content_title: "Delete community content",
		alert_delete_community_content: (folder) =>
			`Are you sure you want to delete \nthe selected item? The original file in <span class="highlight lineheight">${folder}</span> \nwill not be deleted.`,
		question_mark:
			"Suspended communities excluding administrators \nMember access is restricted.",
		change_setting_btn: "Change community settings",
	},
	_button: {
		accept: "Accept",
		add_new: "Add New",
		add_permission: "Add",
		add: "Add",
		backup: "Backup",
		cancel: "Cancel",
		cancellation: "Cancel",
		check_duplicate_email: "Check email",
		close_community: "Close Community",
		close: "Close",
		create: "Create",
		delete_approval: "Delete Approval",
		delete_community: "Delete Community",
		delete_history: "Delete History",
		delete_permission: "Delete",
		delete_rejected: "Delete Rejected",
		delete: "Delete",
		edit: "Edit",
		exit: "Exit",
		go_to_original: "Go to original",
		login: "Log in",
		move: "Move",
		pause: "Pause",
		refresh: "Refresh",
		reject_deletion: "Reject",
		reject: "Reject",
		reset_email: "Reset email",
		reset_filter: "Reset filter",
		reset_password: "Reset password",
		save: "Save",
		search: "Search",
		signin: "Join in",
	},
	login: {
		policy_text: `This site is protected by reCAPTCHA and the Google <a href="https://policies.google.com/privacy">Privacy Policy</a> and <a href="https://policies.google.com/terms">Terms of Service</a> apply.`,
		or: "or",
	},
};
